#!/bin/bash

case $1 in 
store | erase)
echo "credential-helper does not allow login/logout"
exit 1
;;
get)
BEARER=$(ibmcloud iam oauth-tokens | awk '{ print $4;}')
cat<<EOF
{
	"Username": "iambearer",
	"Secret": "$BEARER"
}
EOF
;;
esac

